{% set name = "terminado" %}
{% set version = "0.7" %}
{% set wheel_tag = "py2.py3" %}
{% set fn = "{}-{}-{}-none-any.whl".format(name, version, wheel_tag) %}
{% set sha256 = "57858bd06c6f20f66971aa62377e14e88995f6d6ec70ded7d1d2fcbdad570c8a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ fn }}
  url: https://pypi.io/packages/{{ wheel_tag }}/{{ name[0] }}/{{ name }}/{{ fn }}
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: pip install --no-deps {{ fn }}

requirements:
  build:
    - python
    - pip
  run:
    - python
    - ptyprocess
    - tornado >=4

test:
  imports:
    - terminado

  requires:
    - nose

  commands:
    - nosetests terminado

about:
  home: http://github.com/mitsuhiko/markupsafe
  license: BSD 3-clause
  summary: Terminals served by tornado websockets
