{% set version = "0.4.1" %}

package:
    name: h5netcdf
    version: {{ version }}

source:
    fn: h5netcdf-{{ version }}.tar.gz
    url: https://github.com/shoyer/h5netcdf/archive/v{{ version }}.tar.gz
    sha256: 0982527e7a1e09019ac5c6f1b332a30f7bbacfbc30f4d5b5249ae4aba29cc986

build:
    number: 0
    noarch: python
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
        - h5py
    run:
        - python
        - h5py

test:
    imports:
        - h5netcdf

about:
    home: https://github.com/shoyer/h5netcdf
    license: BSD 3-Clause
    summary: 'netCDF4 via h5py.'
