{% set name = "bokeh" %}
{% set version = "0.12.7" %}
{% set sha256 = "2c42c95bf1a418c758dbff8446b4f5e5fc72ac10ea5da4e6b5010067396d0880" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - bokeh = bokeh.__main__:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    # use requirements meta-package to account for python version dependencies
    - bokeh_conda_requirements {{ version }}

test:
  requires:
    - matplotlib
  imports:
    - bokeh
    - bokeh.application
    - bokeh.application.handlers
    - bokeh.client
    - bokeh.command
    - bokeh.command.subcommands
    - bokeh.core
    - bokeh.core.compat
    - bokeh.core.compat.mplexporter
    - bokeh.core.compat.mplexporter.renderers
    - bokeh.core.property
    - bokeh.core.validation
    - bokeh.models
    - bokeh.models.widgets
    - bokeh.plotting
    - bokeh.sampledata
    - bokeh.server
    - bokeh.server.views
    - bokeh.sphinxext
    - bokeh.themes
    - bokeh.util

  commands:
    - bokeh --help

about:
  home: http://bokeh.pydata.org/
  license: BSD
  license_file: LICENSE.txt
  summary: Python interactive visualization library for modern web browsers
  description: |
    Bokeh is a Python interactive visualization library that targets
    modern web browsers for presentation. Its goal is to provide elegant,
    concise  construction of novel graphics in the style of D3.js, and to
    extend this capability with high-performance interactivity over very
    large or streaming datasets. Bokeh can help anyone who would like to
    quickly and easily create interactive plots, dashboards, and data
    applications.
  doc_url: http://bokeh.pydata.org/en/latest/docs/user_guide.html
  dev_url: http://github.com/bokeh/bokeh
