{% set version = "0.15.2" %}
{% set hash = "abe6758540fdbc260f14ee71cebc3ab88682e24ff147afa89375b7006f57d3ed" %}

package:
  name: dask
  version: "{{ version }}"

source:
  fn: dask-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/dask/dask-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - bokeh
    - cloudpickle >=0.2.1
    - distributed >=1.16.0
    - numpy
    - pandas >=0.19.0
    - partd >=0.3.7
    - toolz >=0.7.2

test:
  imports:
    - dask
    - dask.array
    - dask.bag
    - dask.bytes
    - dask.dataframe
    - dask.dataframe.tseries
    - dask.delayed
    - dask.diagnostics
    - dask.store

about:
  home: http://github.com/dask/dask/
  license: BSD 3-Clause
  summary: 'Minimal task scheduling abstraction'
