{% set version = "2017.4.17" %}

package:
  name: ca-certificates
  version: {{ version }}

source:
  fn: certifi-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/c/certifi/certifi-{{ version }}.tar.gz
  sha256: f7527ebf7461582ce95f7a9e03dd141ce810d40590834f4ec20cddd54234c10a

build:
  number: 0

test:
  # use system provided curl for testing
  #requires:
  #  - curl

  commands:
    # Verify the certificates are there.
    - test -f "${PREFIX}/ssl/cacert.pem"                                      # [unix]
    - test -f "${PREFIX}/ssl/cert.pem"                                        # [unix]

    # Use the certificates to download something.
    - curl --cacert "${PREFIX}/ssl/cacert.pem" https://www.google.com         # [unix]

about:
  home: https://github.com/conda-forge/ca-certificates-feedstock
  license: ISC
  license_file: LICENSE
  summary: Certificates for use with other packages.
