{%set name = "cryptography" %}
{%set version = "2.1.3" %}
{%set hash_type = "sha256" %}
{%set hash_val = "68a26c353627163d74ee769d4749f2ee243866e9dac43c93bb33ebd8fbed1199" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0

requirements:
  build:
    - python
    - asn1crypto >=0.21.0
    - cffi >=1.4.1
    - enum34           # [py27]
    - idna >=2.1
    - ipaddress        # [py27]
    - openssl 1.0.2*
    - setuptools
    - six >=1.4.1
  run:
    - python
    - asn1crypto >=0.21.0
    - cffi >=1.4.1
    - enum34           # [py27]
    - idna >=2.1
    - ipaddress        # [py27]
    - openssl 1.0.2*
    - setuptools
    - six >=1.4.1

test:
  imports:
    - cryptography
    - cryptography.fernet

about:
  home: https://cryptography.io
  license: Apache
  license_file: LICENSE
  summary: Provides cryptographic recipes and primitives to Python developers
  description: |
    Cryptography is a Python library which exposes cryptographic recipes and
    primitives. The goal is for it to be your "cryptographic standard library".
  doc_url: https://cryptography.io
  dev_url: https://github.com/pyca/cryptography
