{% set version = "2017.11.5" %}

package:
  name: certifi
  version: {{ version }}

source:
  fn: certifi-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/c/certifi/certifi-{{ version }}.tar.gz
  sha256: 5ec74291ca1136b40f0379e1128ff80e866597e4e2c1e755739a913bbc3613c0

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - certifi

about:
  home: http://certifi.io/
  license: ISC
  license_file: LICENSE
  summary: Python package for providing Mozilla's CA Bundle.
