{% set name = "requests" %}
{% set version = "2.18.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: requests-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5b26fcc5e72757a867e4d562333f841eddcef93548908a1bb1a9207260618da9

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - certifi
    - chardet
    - idna
    - urllib3

test:
  imports:
    - requests

about:
  home: http://python-requests.org
  license: Apache 2.0
  summary: 'Python HTTP for Humans.'
