{% set version = "5.2.1" %}

package:
  name: notebook
  version: {{ version }}

source:
  fn: notebook-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/n/notebook/notebook-{{ version }}.tar.gz
  sha256: 4ae5b81dd39b37cdd99dcffe83a5182c849947b92d46ac4d2b5093af2bb9f224


build:
  script: pip install --no-deps .
  number: 0
  noarch: python
  entry_points:
    - jupyter-notebook = notebook.notebookapp:main
    - jupyter-nbextension = notebook.nbextensions:main
    - jupyter-serverextension = notebook.serverextensions:main

requirements:
  build:
    - python
    - pip
  run:
    - ipykernel
    - ipython_genutils
    - jinja2
    - jupyter_core
    - jupyter_client
    - nbconvert
    - nbformat
    - python
    - terminado
    - tornado >=4
    - traitlets >=4.3

test:
  commands:
    - jupyter notebook -h
    - jupyter nbextension -h
    - jupyter serverextension -h
  imports:
    - notebook

about:
  home: http://jupyter.org
  license: BSD 3-clause
  summary: A web-based notebook environment for interactive computing
